// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqomlmgklwtzguzgfzxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxb21sbWdrbHd0emd1emdmenh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMTE5MTQsImV4cCI6MjA1Mjg4NzkxNH0.FD9vwl1BQ7KHC4BB3A5yv4RB6_AW_u0ifmxwL3oPVFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);